/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vva;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Fanilo
 */
public class JFChoixAffichageAnimation extends javax.swing.JFrame {

    private static Compte compte;
    private static javax.swing.JFrame pagePrecedente;
    public JFChoixAffichageAnimation(Compte compte, javax.swing.JFrame pagePrcdt) {
        this.compte = compte;
        this.pagePrecedente = pagePrcdt;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtChoisirEvenement = new javax.swing.JButton();
        jbtChoisirActivite = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCBRetour = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbtChoisirEvenement.setText("EVENEMENT");
        jbtChoisirEvenement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtChoisirEvenementActionPerformed(evt);
            }
        });

        jbtChoisirActivite.setText("ACTIVITES");
        jbtChoisirActivite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtChoisirActiviteActionPerformed(evt);
            }
        });

        jLabel1.setText("CHOISISSEZ LE TYPE D'ANIMATION A AFFICHER");

        jCBRetour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menu" }));
        jCBRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtChoisirActivite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtChoisirEvenement, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jCBRetour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCBRetour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jbtChoisirEvenement, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jbtChoisirActivite, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtChoisirEvenementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtChoisirEvenementActionPerformed
        try {
            JFAffichageEvenement jFAE = new JFAffichageEvenement(compte, this);
            jFAE.setLocationRelativeTo(null);
            jFAE.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(JFChoixAffichageAnimation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtChoisirEvenementActionPerformed

    private void jbtChoisirActiviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtChoisirActiviteActionPerformed
        
        try {
            
            JFAffichageActivite jFAA = new JFAffichageActivite(compte, this);
            jFAA.setLocationRelativeTo(null);
            jFAA.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(JFChoixAffichageAnimation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtChoisirActiviteActionPerformed

    private void jCBRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBRetourActionPerformed
        if(jCBRetour.getSelectedItem() == "Menu")
        {
            JFMenu jFM = new JFMenu(compte);
            jFM.setLocationRelativeTo(null);
            jFM.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_jCBRetourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFChoixAffichageAnimation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFChoixAffichageAnimation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFChoixAffichageAnimation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFChoixAffichageAnimation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFChoixAffichageAnimation(compte, pagePrecedente).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCBRetour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtChoisirActivite;
    private javax.swing.JButton jbtChoisirEvenement;
    // End of variables declaration//GEN-END:variables
}
