/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vva;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Fanilo
 */
public class JFChoixTypeAnimation extends javax.swing.JFrame {

    /**
     * Creates new form CreerAnimation
     */
    private static Compte compte;
    private static javax.swing.JFrame pagePrecedente;

    public JFChoixTypeAnimation(Compte c, javax.swing.JFrame pagePrcdt) {
        initComponents();
        
        this.pagePrecedente = pagePrcdt;       
        this.compte = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCBRetour = new javax.swing.JComboBox<>();
        jBEvenement = new javax.swing.JButton();
        jBActivite = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCBRetour1 = new javax.swing.JComboBox<>();

        jCBRetour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menu" }));
        jCBRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBRetourActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBEvenement.setText("EVENEMENT");
        jBEvenement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEvenementActionPerformed(evt);
            }
        });

        jBActivite.setText("ACTIVITE");
        jBActivite.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBActivite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActiviteActionPerformed(evt);
            }
        });

        jLabel1.setText("Choisissez le type d'animation que vous désirez proposer.");

        jCBRetour1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menu", "Page précédente" }));
        jCBRetour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBRetour1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBEvenement, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(jBActivite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(83, 83, 83)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBRetour1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCBRetour1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jBActivite, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addComponent(jBEvenement, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBActiviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActiviteActionPerformed
        try { 
            JFPlanifierActivite jFPA = new JFPlanifierActivite(compte, this);
            jFPA.setLocationRelativeTo(null);
            jFPA.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(JFChoixTypeAnimation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBActiviteActionPerformed

    private void jBEvenementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEvenementActionPerformed
        try {
           
            
            JFPlanifierEvenement jFPE = new JFPlanifierEvenement(compte, this);
            jFPE.setLocationRelativeTo(null);
            jFPE.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(JFChoixTypeAnimation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBEvenementActionPerformed

    private void jCBRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBRetourActionPerformed
        if(jCBRetour.getSelectedItem() == "Menu")
        {
            JFMenu jFM = new JFMenu(compte);
            jFM.setLocationRelativeTo(null);
            jFM.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jCBRetourActionPerformed

    private void jCBRetour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBRetour1ActionPerformed
        if(jCBRetour.getSelectedItem() == "Page précédente")
        {
            this.pagePrecedente.setLocationRelativeTo(null);
            this.pagePrecedente.setVisible(true);
            this.dispose();
        }
        else
        {
            JFMenu jFM = new JFMenu(compte);
            jFM.setLocationRelativeTo(null);
            jFM.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jCBRetour1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFChoixTypeAnimation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFChoixTypeAnimation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFChoixTypeAnimation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFChoixTypeAnimation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFChoixTypeAnimation(compte, pagePrecedente).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActivite;
    private javax.swing.JButton jBEvenement;
    private javax.swing.JComboBox<String> jCBRetour;
    private javax.swing.JComboBox<String> jCBRetour1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
